apiVersion: v1
kind: Service
metadata:
  name: testegoogle
  namespace: default
  labels:
    app: testegoogle
spec:
  selector:
    app: testegoogle
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
