apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: gcr.io/mobyware-teste/testegoogle
      context: ../teste-google
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
